### ISSUE TITLE
Typo: Order of type-assert and default-value reversed

### ISSUE THREAD

**Issue by dojt** [TartuQC/qccdSimulator#18]
https://github.com/TartuQC/qccdSimulator/blob/f1b66868c21d5e62662aed4595d511f4d6d24db6/src/qccdevcontrol.jl#L59

It should be:
```
function f(;
                 blah :: Type = default
                 )
```
... but I wrote it the other way twice (some type errors are not caught).

**Comment by Hopery** [comment]
Done :+1:
